"""
Bootstrap SSM Terraform Service

Generates Terraform to attach SSM IAM profile to existing instances
Optionally creates VPC endpoints for private subnets
"""
import logging
import json
import time
from pathlib import Path
from typing import List, Dict
import boto3
from botocore.exceptions import ClientError

logger = logging.getLogger(__name__)


def generate_bootstrap_ssm_terraform(
    instance_ids: List[str],
    vpc_id: str = None,
    subnet_ids: List[str] = None,
    create_vpc_endpoints: bool = False
) -> str:
    """
    Generate Terraform to bootstrap SSM on existing instances.
    
    Args:
        instance_ids: List of EC2 instance IDs to bootstrap
        vpc_id: VPC ID (required if create_vpc_endpoints=True)
        subnet_ids: Subnet IDs for VPC endpoints
        create_vpc_endpoints: Whether to create SSM VPC endpoints
    
    Returns:
        Terraform configuration string
    """
    lines = [
        '# Bootstrap SSM for Existing Instances',
        '# Auto-generated by DAC',
        '',
        'terraform {',
        '  required_version = ">= 1.0"',
        '  required_providers {',
        '    aws = {',
        '      source  = "hashicorp/aws"',
        '      version = "~> 5.0"',
        '    }',
        '  }',
        '}',
        '',
        'variable "aws_region" {',
        '  default = "eu-north-1"',
        '}',
        '',
        'provider "aws" {',
        '  region = var.aws_region',
        '}',
        '',
        '# IAM Role for SSM',
        'data "aws_iam_policy_document" "ssm_assume_role" {',
        '  statement {',
        '    actions = ["sts:AssumeRole"]',
        '    principals {',
        '      type        = "Service"',
        '      identifiers = ["ec2.amazonaws.com"]',
        '    }',
        '  }',
        '}',
        '',
        'resource "aws_iam_role" "ssm_bootstrap" {',
        '  name               = "dac-ssm-bootstrap-role"',
        '  assume_role_policy = data.aws_iam_policy_document.ssm_assume_role.json',
        '}',
        '',
        'resource "aws_iam_role_policy_attachment" "ssm_bootstrap" {',
        '  role       = aws_iam_role.ssm_bootstrap.name',
        '  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"',
        '}',
        '',
        'resource "aws_iam_instance_profile" "ssm_bootstrap" {',
        '  name = "dac-ssm-bootstrap-profile"',
        '  role = aws_iam_role.ssm_bootstrap.name',
        '}',
        '',
    ]
    
    # Attach instance profile to each instance
    for idx, instance_id in enumerate(instance_ids):
        lines.extend([
            f'# Attach SSM profile to {instance_id}',
            f'resource "aws_iam_instance_profile_association" "ssm_{idx}" {{',
            f'  instance_profile_name = aws_iam_instance_profile.ssm_bootstrap.name',
            f'  instance_id           = "{instance_id}"',
            f'',
            f'  # Force replacement if profile changes',
            f'  lifecycle {{',
            f'    create_before_destroy = true',
            f'  }}',
            f'}}',
            f'',
        ])
    
    # VPC Endpoints (optional)
    if create_vpc_endpoints and vpc_id:
        if not subnet_ids:
            subnet_ids = []
        
        subnet_ids_tf = '[' + ', '.join([f'"{sid}"' for sid in subnet_ids]) + ']'
        
        lines.extend([
            '# VPC Endpoints for SSM (private subnet)',
            f'data "aws_vpc" "target" {{',
            f'  id = "{vpc_id}"',
            f'}}',
            '',
            f'data "aws_security_group" "default" {{',
            f'  vpc_id = data.aws_vpc.target.id',
            f'  name   = "default"',
            f'}}',
            '',
            '# SSM Endpoint',
            'resource "aws_vpc_endpoint" "ssm" {',
            '  vpc_id              = data.aws_vpc.target.id',
            '  service_name        = "com.amazonaws.${var.aws_region}.ssm"',
            '  vpc_endpoint_type   = "Interface"',
            f'  subnet_ids          = {subnet_ids_tf}',
            '  security_group_ids  = [data.aws_security_group.default.id]',
            '  private_dns_enabled = true',
            '}',
            '',
            '# EC2 Messages Endpoint',
            'resource "aws_vpc_endpoint" "ec2messages" {',
            '  vpc_id              = data.aws_vpc.target.id',
            '  service_name        = "com.amazonaws.${var.aws_region}.ec2messages"',
            '  vpc_endpoint_type   = "Interface"',
            f'  subnet_ids          = {subnet_ids_tf}',
            '  security_group_ids  = [data.aws_security_group.default.id]',
            '  private_dns_enabled = true',
            '}',
            '',
            '# SSM Messages Endpoint',
            'resource "aws_vpc_endpoint" "ssmmessages" {',
            '  vpc_id              = data.aws_vpc.target.id',
            '  service_name        = "com.amazonaws.${var.aws_region}.ssmmessages"',
            '  vpc_endpoint_type   = "Interface"',
            f'  subnet_ids          = {subnet_ids_tf}',
            '  security_group_ids  = [data.aws_security_group.default.id]',
            '  private_dns_enabled = true',
            '}',
            '',
        ])
    
    lines.extend([
        '# Outputs',
        'output "iam_role_arn" {',
        '  value = aws_iam_role.ssm_bootstrap.arn',
        '}',
        '',
        'output "instance_profile_name" {',
        '  value = aws_iam_instance_profile.ssm_bootstrap.name',
        '}',
        '',
    ])
    
    return '\\n'.join(lines)


def _get_instance_profile_assoc(ec2, instance_id: str):
    try:
        resp = ec2.describe_iam_instance_profile_associations(
            Filters=[{"Name": "instance-id", "Values": [instance_id]}]
        )
        for assoc in resp.get("IamInstanceProfileAssociations", []):
            if assoc.get("State") != "disassociated":
                return assoc
    except ClientError as e:
        logger.error("Failed to describe profile association for %s: %s", instance_id, e)
    return None


def wait_for_ssm_online(
    instance_ids: List[str],
    region: str,
    aws_access_key: str,
    aws_secret_key: str,
    attempts: int = 6,
    delay_seconds: int = 20,
) -> Dict:
    """Poll SSM PingStatus for given instances.

    Returns mapping instance_id -> {status, platform, agent_version}
    """
    ssm = boto3.client(
        "ssm",
        region_name=region,
        aws_access_key_id=aws_access_key,
        aws_secret_access_key=aws_secret_key,
    )

    states: Dict[str, Dict] = {iid: {"status": "unknown"} for iid in instance_ids}

    for attempt in range(attempts):
        try:
            resp = ssm.describe_instance_information(
                Filters=[{"Key": "InstanceIds", "Values": instance_ids}]
            )
            for info in resp.get("InstanceInformationList", []):
                iid = info.get("InstanceId")
                states[iid] = {
                    "status": info.get("PingStatus"),
                    "platform": info.get("PlatformType"),
                    "agent_version": info.get("AgentVersion"),
                }
        except ClientError as e:
            logger.error("wait_for_ssm_online describe failed: %s", e)

        # If any Online, we can stop early but still return all states
        if any(s.get("status") == "Online" for s in states.values()):
            break

        if attempt < attempts - 1:
            time.sleep(delay_seconds)

    return states


def bootstrap_ssm_for_instances(
    instance_ids: List[str],
    work_dir: Path,
    vpc_id: str = None,
    subnet_ids: List[str] = None,
    create_vpc_endpoints: bool = False,
    aws_access_key: str = None,
    aws_secret_key: str = None,
    region: str = "eu-north-1"
) -> Dict:
    """
    Bootstrap SSM for existing instances.
    
    Returns:
        {"status": "success|failed", "terraform_path": "...", "message": "..."}
    """
    logger.info(" Bootstrapping SSM for %d instances", len(instance_ids))
    
    # Generate Terraform
    tf_content = generate_bootstrap_ssm_terraform(
        instance_ids=instance_ids,
        vpc_id=vpc_id,
        subnet_ids=subnet_ids,
        create_vpc_endpoints=create_vpc_endpoints
    )
    
    # Save to file
    tf_dir = work_dir / "bootstrap_ssm"
    tf_dir.mkdir(parents=True, exist_ok=True)
    tf_file = tf_dir / "main.tf"
    tf_file.write_text(tf_content)
    
    logger.info(" Bootstrap Terraform saved: %s", tf_file)
    
    return {
        "status": "success",
        "terraform_path": str(tf_file),
        "message": f"Bootstrap SSM Terraform generated for {len(instance_ids)} instances. Run terraform apply to attach SSM profiles.",
        "instance_ids": instance_ids,
        "vpc_endpoints_enabled": create_vpc_endpoints,
    }


def bootstrap_ssm_attach_profile(
    instance_ids: List[str],
    region: str,
    aws_access_key: str,
    aws_secret_key: str,
    role_name: str = "dac-ssm-bootstrap-role",
    instance_profile_name: str = "dac-ssm-bootstrap-profile"
) -> Dict:
    """
    Attach (or create) SSM IAM role/profile to existing instances without Terraform.

    Steps:
    - Ensure IAM role exists with AmazonSSMManagedInstanceCore
    - Ensure instance profile exists and contains the role
    - Associate profile to each instance
    """
    iam = boto3.client(
        "iam",
        aws_access_key_id=aws_access_key,
        aws_secret_access_key=aws_secret_key,
        region_name=region,
    )
    ec2 = boto3.client(
        "ec2",
        aws_access_key_id=aws_access_key,
        aws_secret_access_key=aws_secret_key,
        region_name=region,
    )

    actions = []

    # Ensure role
    role_arn = None
    try:
        role = iam.get_role(RoleName=role_name)
        role_arn = role["Role"]["Arn"]
        actions.append(f"Reuse role {role_name}")
    except ClientError:
        assume_doc = {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {"Service": "ec2.amazonaws.com"},
                    "Action": "sts:AssumeRole",
                }
            ],
        }
        resp = iam.create_role(RoleName=role_name, AssumeRolePolicyDocument=json.dumps(assume_doc))
        role_arn = resp["Role"]["Arn"]
        actions.append(f"Create role {role_name}")

    # Ensure policy attachment
    try:
        iam.attach_role_policy(
            RoleName=role_name,
            PolicyArn="arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
        )
        actions.append("Attach AmazonSSMManagedInstanceCore policy")
    except ClientError as e:
        logger.error("Failed to attach policy: %s", e)
        return {"status": "failed", "error": str(e), "actions": actions}

    # Ensure instance profile
    profile_exists = False
    try:
        iam.get_instance_profile(InstanceProfileName=instance_profile_name)
        profile_exists = True
        actions.append(f"Reuse instance profile {instance_profile_name}")
    except ClientError:
        iam.create_instance_profile(InstanceProfileName=instance_profile_name)
        actions.append(f"Create instance profile {instance_profile_name}")

    # Add role to profile if missing
    try:
        iam.add_role_to_instance_profile(
            InstanceProfileName=instance_profile_name,
            RoleName=role_name,
        )
        actions.append("Attach role to profile")
    except ClientError as e:
        if e.response["Error"].get("Code") not in {"LimitExceeded", "EntityAlreadyExists"}:
            # Ignore if already attached
            logger.error("Failed to add role to profile: %s", e)
            return {"status": "failed", "error": str(e), "actions": actions}

    # Associate profile to instances with safeguards
    associated = []
    skipped = []
    blocked = []
    for iid in instance_ids:
        assoc = _get_instance_profile_assoc(ec2, iid)
        if assoc:
            current_name = assoc.get("IamInstanceProfile", {}).get("Name")
            if current_name == instance_profile_name:
                actions.append(f"{iid}: profile already attached -> no-op")
                skipped.append(iid)
                continue
            # Existing profile different: do NOT replace automatically
            blocked.append({
                "instance_id": iid,
                "reason": "EXISTING_PROFILE",
                "current_profile": current_name,
                "message": "Instance already has a different profile; replacement requires explicit approval."
            })
            actions.append(f"{iid}: existing profile {current_name} -> not replaced")
            continue

        try:
            ec2.associate_iam_instance_profile(
                IamInstanceProfile={"Name": instance_profile_name},
                InstanceId=iid,
            )
            associated.append(iid)
        except ClientError as e:
            actions.append(f"Failed to attach to {iid}: {e}")
            logger.error("Cannot attach profile to %s: %s", iid, e)

    status = "success" if associated or skipped else "failed"
    return {
        "status": status,
        "associated_instances": associated,
        "skipped_instances": skipped,
        "blocked_instances": blocked,
        "iam_role_arn": role_arn,
        "instance_profile_name": instance_profile_name,
        "actions": actions,
    }
