"""Add Plan and PlanExecution models for structured execution

Revision ID: 397172036b25
Revises: f8abc996ce80
Create Date: 2026-01-24 22:57:34.843440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397172036b25'
down_revision: Union[str, Sequence[str], None] = 'f8abc996ce80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raw_prompt', sa.String(length=5000), nullable=False),
    sa.Column('infra_requirements', sa.JSON(), nullable=True),
    sa.Column('config_requirements', sa.JSON(), nullable=True),
    sa.Column('verification_requirements', sa.JSON(), nullable=True),
    sa.Column('audit_requirements', sa.JSON(), nullable=True),
    sa.Column('kubernetes_requirements', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50000), nullable=True),
    sa.Column('output', sa.String(length=50000), nullable=True),
    sa.Column('errors', sa.String(length=5000), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('execution_started', sa.DateTime(), nullable=True),
    sa.Column('execution_ended', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_executions')
    op.drop_table('plans')
    # ### end Alembic commands ###
